[package]
name = "paypal-rs"
version = "0.2.4"
authors = ["Edgar <git@edgarluque.com>"]
description = "A library that wraps the paypal api asynchronously."
repository = "https://github.com/edg-l/paypal-rs/"
license = "MIT OR Apache-2.0"
keywords = ["paypal", "paypal-api"]
categories = ["api-bindings", "web-programming::http-client"]
documentation = "https://docs.rs/paypal-rs"
readme = "README.md"
edition = "2021"


[dependencies]
reqwest = { version = "0.11.12", default-features = false, features = ["json"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
serde_with = "2.0.1"
chrono = { version = "0.4.22", features = ["serde"] }
jsonwebtoken = "8.1.1"
base64 = "0.13.1"
log = "0.4.17"
bytes = "1.2.1"
derive_builder = "0.11.2"
serde_qs = "0.10.1"

[dev-dependencies]
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
dotenvy = "0.15.6"
color-eyre = "0.6.2"
wiremock = "0.5.15"

[features]
default = ["reqwest/native-tls"]
rustls = ["reqwest/rustls-tls"]
